language: r
r:
  - release
  - devel
cache: packages
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  # sf system requirements
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  # ncdf4 system requirements
  - sudo apt-get install -y netcdf-bin libnetcdf-dev netcdf-bin

r_github_packages:
  - tidyverse/ggplot2
  - dgrtwo/gganimate

after_success:
  - Rscript -e 'covr::codecov()'

env:
   global:
     - R_LIBS="https://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""
